## Task 1:

#### 1. Write a function to compute 5/0 and use try/except to catch the exceptions.

In [1]:
def compute(n):
    try:
        print(5/n)
    except Exception as e:
        print(e)
    else:
        print('Computation happened properly')

In [2]:
compute(2)

2.5
Computation happened properly


In [3]:
compute(0)

division by zero


#### 2. Implement a Python program to generate all sentences where subject is in ["Americans","Indians"] and verb is in ["Play", "watch"] and the object is in ["Baseball","cricket"].
#### Hint: Subject,Verb and Object should be declared in the program as shown below.
subjects=["Americans ","Indians"]

verbs=["play","watch"]

objects=["Baseball","Cricket"]

#### Output should come as below:
Americans play Baseball.

Americans play Cricket.

Americans watch Baseball.

Americans watch Cricket.

Indians play Baseball.

Indians play Cricket.

Indians watch Baseball.

Indians watch Cricket.

In [2]:
subjects = ['Americans', 'Indians']
verbs = ['play', 'watch']
objects = ['Baseball', 'Cricket']
for s in subjects:
    for v in verbs:
        for o in objects:
            print(s + ' ' + v + ' ' + o)

Americans play Baseball
Americans play Cricket
Americans watch Baseball
Americans watch Cricket
Indians play Baseball
Indians play Cricket
Indians watch Baseball
Indians watch Cricket


## Task 2:

#### 1. Write a function so that the columns of the output matrix are powers of the input vector.

#### The order of the powers is determined by the increasing boolean argument. Specifically, when increasing is False, the i-th output column is the input vector raised element-wise to the power of N - i - 1.

#### HINT: Such a matrix with a geometric progression in each row is named for AlexandreTheophile Vandermonde.

In [15]:
import numpy as np

In [21]:
def genVandermondeMatrix(vector, columnLen, increasing):
    lenVector = len(vector)
    if increasing == True:
        return np.array([num**x for num in vector for x in range(columnLen)]).reshape(lenVector, columnLen)
    elif increasing == False:
        return np.array([num**x for num in vector for x in range(columnLen-1,-1,-1)]).reshape(lenVector, columnLen)

In [36]:
ipVector = np.array([1,2,3,4,5]) # Input Vector
colLength = 5 # Length of columns
isIncreasing = True

In [37]:
genVandermondeMatrix(ipVector, colLength, isIncreasing)

array([[  1,   1,   1,   1,   1],
       [  1,   2,   4,   8,  16],
       [  1,   3,   9,  27,  81],
       [  1,   4,  16,  64, 256],
       [  1,   5,  25, 125, 625]])

In [39]:
isIncreasing = False
genVandermondeMatrix(ipVector, colLength, isIncreasing)

array([[  1,   1,   1,   1,   1],
       [ 16,   8,   4,   2,   1],
       [ 81,  27,   9,   3,   1],
       [256,  64,  16,   4,   1],
       [625, 125,  25,   5,   1]])

In [41]:
colLength = 8
genVandermondeMatrix(ipVector, colLength, isIncreasing)

array([[    1,     1,     1,     1,     1,     1,     1,     1],
       [  128,    64,    32,    16,     8,     4,     2,     1],
       [ 2187,   729,   243,    81,    27,     9,     3,     1],
       [16384,  4096,  1024,   256,    64,    16,     4,     1],
       [78125, 15625,  3125,   625,   125,    25,     5,     1]])